title: WangZhenya(王振亚)
logo: /assets/img/AshiakerWang.jpg
description:PhD candidate in Beijing University of Posts and Telecommunications
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
